### ISSUE TITLE
ISBN search failing 

### ISSUE THREAD

**Issue by Annwenn** [felipesere/faros#75]
I'm using both the ISBN-10 and ISBN-13 of a book, which results in

```
[info] GET /api/books/lookup
[debug] Processing by Faros.Books.Controller.lookup/2
  Parameters: %{"isbn" => "2324008939", "title" => ""}
  Pipelines: [:api]
[info] Sent 500 in 3351ms
[error] #PID<0.418.0> running Faros.Endpoint terminated
Server: localhost:4000 (http)
Request: GET /api/books/lookup?isbn=2324008939&title=
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Poison.Encoder.BitString.chunk_size/3
        (poison) lib/poison/encoder.ex:92: Poison.Encoder.BitString.chunk_size(<<195, 106, 117, 103, 195, 115>>, nil, 13)
        (poison) lib/poison/encoder.ex:87: Poison.Encoder.BitString.escape/2
        (poison) lib/poison/encoder.ex:49: Poison.Encoder.BitString.encode/2
        (poison) lib/poison/encoder.ex:156: anonymous fn/4 in Poison.Encoder.Map.encode/2
        (stdlib) lists.erl:1262: :lists.foldl/3
        (poison) lib/poison/encoder.ex:157: Poison.Encoder.Map.encode/2
        (poison) lib/poison/encoder.ex:156: anonymous fn/4 in Poison.Encoder.Map.encode/2
        (stdlib) lists.erl:1262: :lists.foldl/3
Compiled web/views/page_view.ex
[info] GET /api/books/lookup
[debug] Processing by Faros.Books.Controller.lookup/2
  Parameters: %{"isbn" => "978-2324008931", "title" => ""}
  Pipelines: [:api]
[info] Sent 500 in 3447ms
[error] #PID<0.431.0> running Faros.Endpoint terminated
Server: localhost:4000 (http)
Request: GET /api/books/lookup?isbn=978-2324008931&title=
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Poison.Encoder.BitString.chunk_size/3
        (poison) lib/poison/encoder.ex:92: Poison.Encoder.BitString.chunk_size(<<195, 106, 117, 103, 195, 115>>, nil, 13)
        (poison) lib/poison/encoder.ex:87: Poison.Encoder.BitString.escape/2
        (poison) lib/poison/encoder.ex:49: Poison.Encoder.BitString.encode/2
        (poison) lib/poison/encoder.ex:156: anonymous fn/4 in Poison.Encoder.Map.encode/2
        (stdlib) lists.erl:1262: :lists.foldl/3
        (poison) lib/poison/encoder.ex:157: Poison.Encoder.Map.encode/2
        (poison) lib/poison/encoder.ex:156: anonymous fn/4 in Poison.Encoder.Map.encode/2
        (stdlib) lists.erl:1262: :lists.foldl/3
```

**Comment by felipesere** [comment]
That seems really odd!
Is this the book you were trying to find? http://www.amazon.co.uk/Orgueil-pr%C3%A9jug%C3%A9s-Jane-Austen/dp/2324008939/ref=sr_1_1?ie=UTF8&qid=1447024962&sr=8-1&keywords=9782324008931

It seems like something in `Poison` isn't happy with with the umlaute  in `préjugés`

**Comment by Annwenn** [comment]
Either it's Poison's fault, or it's because of the JSON's encoding. Maybe @devinus has an idea about that?

**Comment by devinus** [comment]
`<<195, 106, 117, 103, 195, 115>>` isn't valid UTF-8, could probably use a better error message.

**Comment by felipesere** [comment]
Does that mean we are getting funky JSON? I copied the JSON structure that I get back from the Google Books API into a test and it ran fine...

**Comment by devinus** [comment]
@felipesere Definitely seems like it.
